export const BROWSER_ACTIONS = [
  "status",
  "attach",
  "detach",
  "list_tabs",
  "open_dedicated",
  "batch",
  "get_tab",
  "activate_tab",
  "open_tab",
  "close_tab",
  "duplicate_tab",
  "list_windows",
  "new_window",
  "focus_window",
  "navigate",
  "back",
  "forward",
  "reload",
  "stop",
  "wait_for_navigation",
  "snapshot",
  "screenshot",
  "get_text",
  "get_html",
  "get_attribute",
  "get_url",
  "get_title",
  "find",
  "click",
  "double_click",
  "right_click",
  "hover",
  "type",
  "fill",
  "clear",
  "press_key",
  "key_down",
  "key_up",
  "scroll",
  "drag",
  "select_option",
  "check",
  "uncheck",
  "focus",
  "evaluate",
  "wait_for",
  "handle_dialog",
  "print_pdf",
  "download",
  "list_downloads",
  "cancel_download",
  "network_enable",
  "network_events",
  "console",
] as const;

export type BrowserAction = (typeof BROWSER_ACTIONS)[number];

// Device bootstrap uses open_dedicated internally when open_session has no
// explicit tab_id. Keep it in the wire manifest for cross-repo convergence,
// but do not expose it as a direct ChatGPT browser command.
export const PUBLIC_BROWSER_ACTIONS = BROWSER_ACTIONS.filter(
  (action): action is Exclude<BrowserAction, "open_dedicated"> => action !== "open_dedicated",
);

const MUTATING_BROWSER_ACTIONS = new Set<BrowserAction>([
  "attach",
  "detach",
  "batch",
  "activate_tab",
  "open_tab",
  "close_tab",
  "duplicate_tab",
  "new_window",
  "focus_window",
  "navigate",
  "back",
  "forward",
  "reload",
  "stop",
  "click",
  "double_click",
  "right_click",
  "hover",
  "type",
  "fill",
  "clear",
  "press_key",
  "key_down",
  "key_up",
  "scroll",
  "drag",
  "select_option",
  "check",
  "uncheck",
  "focus",
  "evaluate",
  "handle_dialog",
  "print_pdf",
  "download",
  "cancel_download",
  "network_enable",
]);

export function actionMutatesBrowser(action: BrowserAction): boolean {
  return MUTATING_BROWSER_ACTIONS.has(action);
}
